### ISSUE TITLE
The manifold doesn't looks right

### ISSUE THREAD

**Issue by ur-licht** [dyballa/NeuralEncodingManifolds#1]
Hi, I've been interested in your work and I tried to reproduce the V1 manifold with your data, but I couldn't get the continuous manifold as you showed in your paper. I looked into the NTF result which seems fine:
![V1factor](https://github.com/dyballa/NeuralEncodingManifolds/assets/69672647/b3b4cc8d-b846-404f-9007-758448855622)
But using that to get the manifold will result in something like this:
![V1_manifold](https://github.com/dyballa/NeuralEncodingManifolds/assets/69672647/19e59a1b-79a6-412d-b3b6-d236eb733b51)
If you have any idea what's going wrong, could you please tell me? Thanks a lot.

**Comment by dyballa** [comment]
Hello, thanks for your interest! Would you please share the code you used to produce the manifold?

**Comment by ur-licht** [comment]
Hi, thanks for noticing this issue. My code is the same with yours, except for a program to process the data into tensors, perhaps that's where the problem is (although I couldn't figure it out).
Basically, I ran the 'preprocess.ipynb' to get allT, sigT, maxFRs, zeroed stims for both retina and V1 data, these were used for NTF and computing manifold. Then I did NTF with matlab program, then chose best R, and finally ran the 'encoding-manifold.ipynb'.
In the file I uploaded, just put the 4 data files in 'data' folder it could run.
[NeuralEncodingManifolds-main.zip](https://github.com/dyballa/NeuralEncodingManifolds/files/15301807/NeuralEncodingManifolds-main.zip)

**Comment by ur-licht** [comment]
And here's the factors I get for retina and V1 data. If the factors are correct, with this, NTF is no longer needed (which is quite slow). Looking forward to your reply!
[factors.zip](https://github.com/dyballa/NeuralEncodingManifolds/files/15301932/factors.zip)

**Comment by dyballa** [comment]
Finally found the bug in your code!

In the 4th code cell of your preprocess.ipynb notebook, you have the following line:
```V1_sigT = V1_allT```
after which you proceed to zero-out the statistically non-significant psths from `V1_sigT`.

However, in Python this statement does not create a copy of the `V1_allT` object. It simply copies a reference to it, so `V1_sigT` really points to the same object as `V1_allT`. Therefore when you zeroed-out entries in `V1_sigT` you also inadvertently zeroed-out those same entries in the original `V1_allT`.

And that's what's causing the issue: ultimately, the tensor you use to produce the neural matrix does not include any of the non-significant responses. To fix this, all you need is to change that line into:
```V1_sigT = V1_allT.copy()```

Once I do that and run your code, followed by the steps in `encoding-manifold.ipynb`, this is the result I get:
![fixed](https://github.com/dyballa/NeuralEncodingManifolds/assets/9109434/cfba5506-19af-40b2-b686-f2d4982dc8de)

which is quite similar to the figure in the paper. (Note that, by the stochastic nature of the tensor decomposition step, you will never get an identical result. Also, you might have to rotate or flip coordinates—due to the arbitrary signs of PCs—to find a good angle for viewing the resulting manifold in 3D.)

Thank you so much for testing all this code! You've done an excellent good job reading the source data and producing the corresponding tensors. Would be happy to answer any further questions you might have. Feel free to email me as well.

**Comment by ur-licht** [comment]
That's an embarrassing bug orz... thank you for solving my issue!
